// frontend/src/components/global/Footer.svelte
<script>
	import Twitter from 'lucide-svelte/icons/twitter';
	import Linkedin from 'lucide-svelte/icons/linkedin';
	import Youtube from 'lucide-svelte/icons/youtube';
	import Github from 'lucide-svelte/icons/github';

	import Button from '$lib/components/ui/button/button.svelte';

	const navigationItems = [
		{
			title: 'About',
			items: [
				{
					title: 'What is Microcks ?',
					href: 'https://microcks.io'
				},
				{
					title: 'About Hub.Microcks.io',
					href: 'https://microcks.io/blog/microcks-hub-announcement/'
				},
				{
					title: 'Documentation',
					href: 'https://microcks.io/documentation/getting-started/'
				},
				{
					title: 'Privacy Policy',
					href: 'https://www.linuxfoundation.org/legal/privacy-policy'
				}
			]
		}
	];
</script>

<footer class="w-full py-8 text-foreground">
	<div class="container mx-auto">
		<div class="grid lg:grid-cols-2 gap-10 items-center">
			<div class="flex gap-8 flex-col items-start">
				<div class="flex gap-4 flex-col">
					<h2 class="text-lg md:text-2xl max-w-xl font-regular text-left">Microcks</h2>
					<p class="text-lg max-w-lg text-foreground/75 text-left">
						Microcks is an open source Kubernetes native platform for mocking APIs and
						microservices, allowing contract testing in an automated and scalable way.
					</p>
					<a href="https://microcks.io/documentation/getting-started/" target="_blank">
						<Button>Jump start with Microcks</Button>
					</a>
				</div>
			</div>
			<div class="grid lg:grid-cols-1 gap-10 items-start">
				{#each navigationItems as item (item.title)}
					<div class="flex text-base gap-1 flex-col items-center">
						<div class="flex flex-col gap-2">
							<p class="text-xl">{item.title}</p>
							{#if item.items}
								{#each item.items as subItem (subItem.title)}
									<a href={subItem.href} class="flex justify-between items-center" target="_blank">
										<span class="text-foreground/75">{subItem.title}</span>
									</a>
								{/each}
							{/if}
						</div>
					</div>
				{/each}
			</div>
		</div>
		<div class="w-full h-auto py-6 flex row items-center justify-center gap-2">
			<a
				class="text-foreground p-2 rounded-full flex items-center w-auto h-auto border border-foreground hover:text-primary hover:border-primary"
				href="https://twitter.com/microcksio"
				target="_blank"
			>
				<Twitter strokeWidth={1} />
			</a>
			<a
				class="text-foreground p-2 rounded-full flex items-center w-auto h-auto border border-foreground hover:text-primary hover:border-primary"
				href="https://www.linkedin.com/company/microcks/"
				target="_blank"
			>
				<Linkedin strokeWidth={1} />
			</a>
			<a
				class="text-foreground p-2 rounded-full flex items-center w-auto h-auto border border-foreground hover:text-primary hover:border-primary"
				href="https://www.youtube.com/c/Microcks"
				target="_blank"
			>
				<Youtube strokeWidth={1} />
			</a>
			<a
				class="text-foreground p-2 rounded-full flex items-center w-auto h-auto border border-foreground hover:text-primary hover:border-primary"
				href="https://github.com/microcks"
				target="_blank"
			>
				<Github strokeWidth={1} />
			</a>
		</div>
	</div>
</footer>

// react/src/components/Footer.tsx
// import {
//   FaDiscord,
//   FaGithub,
//   FaLinkedin,
//   FaTwitter,
//   FaYoutube,
// } from "react-icons/fa";

const sections = [
  {
    title: "Microcks",
    links: [
      { name: "What is Microcks?", href: "#" },
      { name: "About hub.microcks.io", href: "#" },
      { name: "Documentation", href: "#" },
      { name: "Privacy Policy", href: "#" },
    ],
  },
  {
    title: "Community",
    links: [
      { name: "GitHub", href: "#" },
      { name: "File an issue", href: "#" },
      { name: "Join Discord", href: "#" },
      { name: "Join Zulip", href: "#" },
    ],
  },
  {
    title: "Socials",
    links: [
      { name: "Twitter", href: "#" },
      { name: "LinkedIn", href: "#" },
      { name: "YouTube", href: "#" },
      { name: "Bluesky", href: "#" },
      { name: "Mastodon", href: "#" },
    ],
  },
];

interface FooterMicrocksProps {
  logo?: {
    url: string;
    src: string;
    alt: string;
    title: string;
  };
}

const Footer = ({
  logo = {
    url: "https://microcks.io",
    // src: "https://hub.microcks.io/assets/images/hub-microcks.svg",
    src:"/microcks.svg",
    alt: "Microcks Logo",
    title: "Microcks.io",
  },
}: FooterMicrocksProps) => {
  return (
    <section className="bg-slate-900 py-24 text-white">
      <div className="container px-4 mx-auto">
        <div className="flex w-full flex-col items-center justify-between gap-10 text-center lg:flex-row lg:items-start lg:text-left">
          {/* Left: Logo + Description + Social Icons */}
          <div className="flex w-full flex-col items-center justify-between gap-6 lg:items-start">
            <div className="flex items-center gap-2">
              <a href={logo.url}>
                <img src={logo.src} alt={logo.alt} className="h-10" />
              </a>
              <h2 className="text-xl font-semibold">{logo.title}</h2>
            </div>
            <p className="text-sm text-gray-300 max-w-xs">
              Microcks is an open-source Kubernetes-native tool for mocking and
              testing APIs and microservices.
            </p>
            {/* <ul className="flex items-center space-x-6 text-gray-300">
              <li className="hover:text-white">
                <a href="#"><FaTwitter className="size-5" /></a>
              </li>
              <li className="hover:text-white">
                <a href="#"><FaLinkedin className="size-5" /></a>
              </li>
              <li className="hover:text-white">
                <a href="#"><FaYoutube className="size-5" /></a>
              </li>
              <li className="hover:text-white">
                <a href="#"><FaGithub className="size-5" /></a>
              </li>
              <li className="hover:text-white">
                <a href="#"><FaDiscord className="size-5" /></a>
              </li>
            </ul> */}
          </div>

          {/* Right: Link Sections */}
          <div className="grid w-full grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8 lg:gap-20">
            {sections.map((section, sectionIdx) => (
              <div key={sectionIdx}>
                <h3 className="mb-4 text-base font-semibold">{section.title}</h3>
                <ul className="space-y-3 text-sm text-gray-300">
                  {section.links.map((link, linkIdx) => (
                    <li
                      key={linkIdx}
                      className="hover:text-white transition-colors"
                    >
                      <a href={link.href}>{link.name}</a>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>

        {/* Bottom Text */}
        <div className="mt-12 flex flex-col justify-between gap-4 border-t border-gray-600 pt-6 text-center text-sm text-gray-400 lg:flex-row lg:items-center lg:text-left">
          <p>© {new Date().getFullYear()} Microcks.io. All rights reserved.</p>
          <ul className="flex justify-center gap-4 lg:justify-start">
            <li className="hover:text-white">
              <a href="#">Terms & Conditions</a>
            </li>
            <li className="hover:text-white">
              <a href="#">Privacy Policy</a>
            </li>
          </ul>
        </div>
      </div>
    </section>
  );
};

export default Footer;
